export const POPULAR_LOCATIONS = [
    "Mumbai, India",
    "Delhi, India",
    "Bangalore, India",
    "London, United Kingdom",
    "New York City, USA",
    "Paris, France",
    "Dubai, UAE",
    "Singapore",
    "Tokyo, Japan",
    "Sydney, Australia",
    "Goa, India",
    "Jaipur, India",
    "Chennai, India",
    "Kolkata, India",
    "Hyderabad, India",
    "Agra, India",
    "Manali, India",
    "Shimla, India",
    "Leh Ladakh, India",
    "Udaipur, India",
    "Kochi, India",
    "Amritsar, India",
    "Bangkok, Thailand",
    "Bali, Indonesia",
    "Rome, Italy",
    "Barcelona, Spain",
    "Amsterdam, Netherlands",
    "Berlin, Germany",
    "Istambul, Turkey",
    "Cairo, Egypt",
    "Cape Town, South Africa",
    "Toronto, Canada",
    "Los Angeles, USA",
    "San Francisco, USA",
    "Zurich, Switzerland",
    "Vienna, Austria",
    "Prague, Czech Republic",
    "Budapest, Hungary"
];
